# Site settings
title: "Tulakan's Resume"
description: ""

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tulakan Ruangrong"
resume_title:                   "Coder"
resume_contact_email:           "tulakan.r@gmail.com"
resume_contact_telephone:       "+6683-298-2626"
resume_contact_address:         "163/24 Khu Bon Rd., Tha Raeng, Bang Khen, Bangkok 10220"
resume_header_contact_info: "163/24 Khu Bon Rd., Tha Raeng, Bang Khen, Bangkok | +6683-298-2626 | tulakan.r@gmail.com"
resume_header_intro: "<p>I have been a general coder who work on demand. One thing that I really like about coding is automation which we can normally see from general purpose programs to data analysis.</p>"
# resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but K.I.S.S.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_language:        true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bluenex/"
  resume_twitter_url:           "https://twitter.com/tulakann"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://facebook.com/tulakann"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://bluenex.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
